Make the free trial banner responsive
Automattic/wc-calypso-bridge pull request #1066
Opened 2023-04-05 17:50 UTC by moon0326

### Changes proposed in this Pull Request:

Closes #1065

This PR makes the free trial notice banner responsive and fixes a few minor glitches. 

1. Render the banner right after the `body` tag so that we don't have to calculate body tag `margin-top` manually.
2. Add media query and set the `--wp-admin--admin-bar--height` manually. As described in #1065, `admin-bar` mu-plugin manually sets `-wp-admin--admin-bar--height`, which makes the browser ignore the media query from the core. Setting `-wp-admin--admin-bar--height` with `!important` is a temporary solution. I'll submit an issue to `admin-bar` mu-plugin to fix the root cause.
3. Hide the free trial banner on a preview screen (screenshot below)

### How to test the changes in this Pull Request:

Since one of the problems came from `admin-bar` mu-plugin, it is better to test this PR on a real trial site with `admin-bar` mu-plugin. Please set up a free trial site, convert it to a dev blog, and copy changes in this PR before testing.

1. Go to /view/:your-site-slug
2. Make sure the banner is not rendered (screenshot 1)
3. Go to the frontend
4. Make sure the banner is rendered right after the admin bar
5. Change your browser width to various sizes and make sure the free trial banner works without breaking words.
6. Make sure the free trial banner works with a few different themes.

### Screenshots
![Screen Shot 2023-04-05 at 10 37 41 AM](https://user-images.githubusercontent.com/4723145/230164177-4831cc77-5abd-46a2-9e16-12a086ae2e27.jpg)

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

2023-04-05 18:12 UTC, moon0326 commented on includes/free-trial/class-wc-calypso-bridge-free-trial-plan-picker-banner.php
> +				add_action( 'wp_head', array( $this, 'add_plan_picker_banner' ), -2000 );
In a normal situation, `wp_body_open` should be used instead. However, `wpcomsh` uses [wp_head](https://github.com/Automattic/wpcomsh/blob/trunk/private-site/private-site.php#L102) hook to render the launch banner (screenshot). In order to render the free trial banner before the launch bar, we also have to use `wp_head` with higher priority.

FYI, when a browser detects an HTML element in the head tag, it actually renders the element in the body correctly.

![Screen Shot 2023-04-05 at 11 10 39 AM](https://user-images.githubusercontent.com/4723145/230167534-87ff26b4-25e5-43d3-958d-4504ea3af2d8.jpg)

2023-04-06 04:11 UTC, ilyasfoo requested changes
Thanks for the quick fix on this, @moon0326!

I spotted a few glitches:

This may not be from this PR, but the banner floats with a top offset when scrolling down. If you confirm this isn't related, I could create a follow-up issue to address it

<img width="489" alt="image" src="https://user-images.githubusercontent.com/3747241/230268053-7a17d248-8e0c-4a63-9301-2fd69d205eb8.png">

2023-04-06 04:11 UTC, ilyasfoo commented on assets/css/free-trial-plan-picker-banner.css
>  	width: 100%;
```suggestion
```

On smaller screens (tested on iPhone XR) it seems there's a white spacing on the right caused by the banner:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/3747241/230267873-bc8641f4-0b90-467f-a7a3-1a1a7891a2bb.png">

I find that removing width actually fixes it without any side effects. Let me know if this works!

<img width="458" alt="image" src="https://user-images.githubusercontent.com/3747241/230269836-d53098f9-8659-466a-a5d9-e6cf8afd86ec.png">

2023-04-06 04:23 UTC, moon0326 commented
> This may not be from this PR, but the banner floats with a top offset when scrolling down. If you confirm this isn't related, I could create a follow-up issue to address it

Thank you!

That's actually a glitch. A fix is on the way 🚗

2023-04-06 04:33 UTC, moon0326 commented
@ilyasfoo Updated in https://github.com/Automattic/wc-calypso-bridge/pull/1066/commits/5606d638794b6f30320104e9a0e9acc7d171ad8f

Thank you!

2023-04-06 05:03 UTC, ilyasfoo approved these changes
Awesome, thanks for the fix! Tested well, LGTM!

2023-04-06 05:22 UTC, chihsuan approved these changes
Looks perfect and tested well! 🚢

2023-04-06 06:09 UTC, merged