Fix payments not working for business plan and move things around
Automattic/wc-calypso-bridge pull request #715
Opened 2021-07-16 13:09 UTC by ilyasfoo

This PR aims to fix the following problems:

1. WCPay menu did not show up for business plan users. This is because our frontend tooling was loaded in `class-wc-calypso-bridge.php`, which actually is only called for Ecommerce plan users.
2. Duplicated codes were made to handle business and ecom users, i.e: nav unification fixes.

This PR would bridge (🥁 ba-dum-tss) shared functionalities between business and ecom plan by sharing a single class. This class would now handle our frontend tooling registration and nav unification fixes.

Apart from that, this PR also moves WCPay-related script registration to `includes/class-wc-calypso-bridge-payments.php`, which seem to be more appropriate.

### Testing instructions

1. Load up this branch and observe everything still works regarding related features.
2. Optionally, for a better coverage please follow the tutorial in p90Yrv-2j7-p2 to test in WPCOM production. If possible, both business and ecommerce plan site is tested.

2021-07-19 20:51 UTC, moon0326 requested changes
Thank you @ilyasfoo for this PR 🎉 It looks good and tested well on prod. One thing I noticed is that the WC Pay icon doesn't render its icon unless you're on the welcome page because `wc-payments.css` is not loaded. The icon looks good once you're on the new welcome page.

Could we load `wp-payments.css` globally for both eCom and business?

2021-07-19 20:58 UTC, moon0326 commented on class-wc-calypso-bridge-shared.php
> +		if ( function_exists( 'wpcomsh_activate_nav_unification' )
I think we have formatting issue here

2021-07-19 21:09 UTC, moon0326 approved these changes

2021-07-22 02:38 UTC, ilyasfoo commented on class-wc-calypso-bridge-shared.php
> +		if ( function_exists( 'wpcomsh_activate_nav_unification' )
Fixed formatting in ceaf3e3

2021-07-22 02:38 UTC, merged